before:
  hooks:
    - go generate ./...
project_name: release
release:
  github:
    owner: mauleyzaola
    name: release
builds:
  - id: release-darwin-amd64
    ldflags:
      - -s -w -X github.com/mauleyzaola/release/pkg/version.Version={{.Version}}
    binary: release
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  - id: release-linux-amd64
    ldflags:
      - -s -w -X github.com/mauleyzaola/release/pkg/version.Version={{.Version}}
    main: ./main.go
    binary: release
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: release-windows-amd64
    ldflags:
      - -s -w -X github.com/mauleyzaola/release/pkg/version.Version={{.Version}}
    main: ./main.go
    binary: release
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"